HeadNode:
  LocalStorage:
    RootVolume:
      Size: 256
      Encrypted: false
      VolumeType: gp3
      Iops: 10000
      Throughput: 1000
  CustomActions:
    OnNodeConfigured:
      Args:
        - 00.install.custom.packages.headnode.sh
        - 02.manual.users.headnode.sh
        - 04.configure.slurm.AllOrNothing.headnode.sh
        - 33.install.cost.control.sh
        - 70.install.enroot.pyxis.sh
      Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
      - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
      - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
      - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      - Policy: arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    S3Access:
      - BucketName: "*"
        EnableWriteAccess: true
  InstanceType: r6i.4xlarge
  Networking:
    ElasticIp: true
    SubnetId: ${HN_SUBNET_ID}
  Ssh:
    KeyName: ${KEY_PAIR}
  Imds:
    Secured: false
Image:
  Os: ubuntu2004
Region: ${AWS_REGION_NAME}
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
    EnableMemoryBasedScheduling: true
  SlurmQueues:
    - Name: cpu48
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 512
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: c6i-12xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: c6i.12xlarge
          MaxCount: 30
          MinCount: 0
        - Name: m6i-12xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: m6i.12xlarge
          MaxCount: 30
          MinCount: 0
        - Name: r6i-12xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: r6i.12xlarge
          MaxCount: 30
          MinCount: 0
        - Name: m5zn-12xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: m5zn.12xlarge
          MaxCount: 30
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 02.manual.users.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 33.install.cost.control.sh
            - 70.install.enroot.pyxis.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/pclusterTagsAndBudget #make sure this policy is created https://pcluster.cloud/02-tutorials/04-cost-tracking.html
        S3Access:
          - BucketName: "*"
            EnableWriteAccess: true
      Networking:
        PlacementGroup:
          Enabled: false
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: cpu32
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 512
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: c6i-8xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: c6i.8xlarge
          MaxCount: 50
          MinCount: 0
        - Name: m6i-8xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: m6i.8xlarge
          MaxCount: 50
          MinCount: 0
        - Name: r6i-8xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: r6i.8xlarge
          MaxCount: 50
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 02.manual.users.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 33.install.cost.control.sh
            - 70.install.enroot.pyxis.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/pclusterTagsAndBudget #make sure this policy is created https://pcluster.cloud/02-tutorials/04-cost-tracking.html
        S3Access:
          - BucketName: "*"
            EnableWriteAccess: true
      Networking:
        PlacementGroup:
          Enabled: false
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: cpu24
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 256
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: m5zn-6xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: m5zn.6xlarge
          MaxCount: 50
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 02.manual.users.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 33.install.cost.control.sh
            - 70.install.enroot.pyxis.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/pclusterTagsAndBudget #make sure this policy is created https://pcluster.cloud/02-tutorials/04-cost-tracking.html
        S3Access:
          - BucketName: "*"
            EnableWriteAccess: true
      Networking:
        PlacementGroup:
          Enabled: false
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: cpu16
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 256
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: c6i-4xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: c6i.4xlarge
          MaxCount: 50
          MinCount: 0
        - Name: m6i-4xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: m6i.4xlarge
          MaxCount: 50
          MinCount: 0
        - Name: r6i-4xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: r6i.4xlarge
          MaxCount: 50
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 02.manual.users.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 33.install.cost.control.sh
            - 70.install.enroot.pyxis.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/pclusterTagsAndBudget #make sure this policy is created https://pcluster.cloud/02-tutorials/04-cost-tracking.html
        S3Access:
          - BucketName: "*"
            EnableWriteAccess: true
      Networking:
        PlacementGroup:
          Enabled: false
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: gpu
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 256
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: p3-2xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: p3.2xlarge
          MaxCount: 100
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 02.manual.users.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 33.install.cost.control.sh
            - 70.install.enroot.pyxis.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/pclusterTagsAndBudget #make sure this policy is created https://pcluster.cloud/02-tutorials/04-cost-tracking.html
        S3Access:
          - BucketName: "*"
            EnableWriteAccess: true
      Networking:
        PlacementGroup:
          Enabled: false
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
SharedStorage:
${ADMINFSX}
Tags:
  - Key: 1Click-HPC
    Value: 'true'
  - Key: 1Click-HPC-version
    Value: 'stability'
  - Key: map-migrated
    Value: ${MAP_MIGRATED}
  - Key: aws-parallelcluster-username
    Value: NA
  - Key: aws-parallelcluster-jobid
    Value: NA
  - Key: aws-parallelcluster-project
    Value: NA
DevSettings:
  Timeouts:
    HeadNodeBootstrapTimeout: 3600
    ComputeNodeBootstrapTimeout: 3600