Region: ${AWS_REGION_NAME}
Image:
  Os: alinux2
DirectoryService:
  DomainName: dc=${DC0},dc=${DC1},dc=${DC2}
  DomainAddr: ldaps://${NLB_PUBLIC_DNS_NAME}
  PasswordSecretArn: ${SECRET_ARN}
  DomainReadOnlyUser: cn=ReadOnlyUser,ou=Users,ou=${OU},dc=${DC0},dc=${DC1},dc=${DC2}
  LdapTlsReqCert: never
  AdditionalSssdConfigs:
    debug_level: "0xFFF0"
    ldap_search_base: dc=research,dc=stability,dc=ai?subtree?(&(!(objectClass=computer))(!(userAccountControl:1.2.840.113556.1.4.803:=2)))
    cache_credentials: False
    enumerate: True
    ldap_user_extra_attrs: "altSecurityIdentities"
    ldap_user_ssh_public_key: "altSecurityIdentities"
HeadNode:
  InstanceType: c5.2xlarge
  CustomActions:
    OnNodeConfigured:
      Args:
        - 00.install.neuron.headnode.sh
        - 02.activate.passwordless.AD.headnode.sh
        - 03.configure.slurm.acct.headnode.sh
        - 33.install.cost.control.sh
      Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
      - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
      - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    S3Access:
      - BucketName: '*'
        EnableWriteAccess: true
  Networking:
    SubnetId: ${HN_SUBNET_ID}
  Ssh:
    KeyName: ${KEY_PAIR}
  LocalStorage:
    RootVolume:
      Size: 1024
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: trainium
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 1024
          EphemeralVolume:
            MountDir: /local_storage
      ComputeResources:
        - Efa:
            Enabled: true
          InstanceType: trn1.32xlarge
          MaxCount: 8
          MinCount: 8
          Name: trn1-32xlarge
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.neuron.trainium.sh
            - 02.activate.passwordless.sudo.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        SubnetIds:
          - ${SUBNET_ID}
        PlacementGroup:
          Enabled: true
SharedStorage:
${FSX}