HeadNode:
  LocalStorage:
    RootVolume:
      Size: 256
      Encrypted: false
      VolumeType: gp3
      Iops: 10000
      Throughput: 1000
  CustomActions:
    OnNodeConfigured:
      Args:
        - 00.install.custom.packages.headnode.sh
        - 02.activate.passwordless.AD.headnode.sh
        - 04.configure.slurm.AllOrNothing.headnode.sh
        - 03.configure.slurm.acct.headnode.sh
        - 10.install.iam.headnode.sh
        - 33.install.cost.control.sh
        - 70.install.enroot.pyxis.sh
        - 88.install.preemption.headnode.sh
      Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
      - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
      - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
      - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      - Policy: arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    S3Access:
      - BucketName: ${S3_BUCKET}
        EnableWriteAccess: true
  InstanceType: c5n.9xlarge
  Networking:
    ElasticIp: true
    SubnetId: ${HN_SUBNET_ID}
  Ssh:
    KeyName: ${KEY_PAIR}
  Imds:
    Secured: false
Image:
  Os: ubuntu2004
DirectoryService:
  DomainName: dc=${DC0},dc=${DC1},dc=${DC2}
  DomainAddr: ldaps://${NLB_PUBLIC_DNS_NAME}
  PasswordSecretArn: ${SECRET_ARN}
  DomainReadOnlyUser: cn=ReadOnlyUser,ou=${OU},dc=${DC0},dc=${DC1},dc=${DC2}
  LdapTlsReqCert: never
  AdditionalSssdConfigs:
    debug_level: "0xFFF0"
    ldap_search_base: dc=research,dc=stability,dc=ai?subtree?(&(!(objectClass=computer))(!(userAccountControl:1.2.840.113556.1.4.803:=2)))
    cache_credentials: False
    enumerate: True
    ldap_user_extra_attrs: "altSecurityIdentities"
    ldap_user_ssh_public_key: "altSecurityIdentities"

Region: ${AWS_REGION_NAME}
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
    EnableMemoryBasedScheduling: true
  SlurmQueues:
    - Name: cpu128
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 1024
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: c6i-32xlarge
          DisableSimultaneousMultithreading: false
          Efa:
            Enabled: true
          InstanceType: c6i.32xlarge
          MaxCount: 50
          MinCount: 0
        - Name: m6i-32xlarge
          DisableSimultaneousMultithreading: false
          Efa:
            Enabled: true
          InstanceType: m6i.32xlarge
          MaxCount: 50
          MinCount: 0
        - Name: r6i-32xlarge
          DisableSimultaneousMultithreading: false
          Efa:
            Enabled: true
          InstanceType: r6i.32xlarge
          MaxCount: 50
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 02.activate.passwordless.sudo.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 10.install.proxy.iam.compute.sh
            - 33.install.cost.control.sh
            - 70.install.enroot.pyxis.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/pclusterTagsAndBudget #make sure this policy is created https://pcluster.cloud/02-tutorials/04-cost-tracking.html
        S3Access:
          - BucketName: ${S3_BUCKET}
            EnableWriteAccess: true
      Networking:
        PlacementGroup:
          Enabled: false
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: cpu64
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 1024
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: c6i-16xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: c6i.16xlarge
          MaxCount: 100
          MinCount: 0
        - Name: m6i-16xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: m6i.16xlarge
          MaxCount: 100
          MinCount: 0
        - Name: r6i-16xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: r6i.16xlarge
          MaxCount: 100
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 02.activate.passwordless.sudo.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 10.install.proxy.iam.compute.sh
            - 33.install.cost.control.sh
            - 70.install.enroot.pyxis.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/pclusterTagsAndBudget #make sure this policy is created https://pcluster.cloud/02-tutorials/04-cost-tracking.html
        S3Access:
          - BucketName: ${S3_BUCKET}
            EnableWriteAccess: true
      Networking:
        PlacementGroup:
          Enabled: false
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: cpu48
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 512
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: c6i-12xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: c6i.12xlarge
          MaxCount: 100
          MinCount: 0
        - Name: m6i-12xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: m6i.12xlarge
          MaxCount: 100
          MinCount: 0
        - Name: r6i-12xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: r6i.12xlarge
          MaxCount: 100
          MinCount: 0
        - Name: m5zn-12xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: m5zn.12xlarge
          MaxCount: 100
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 02.activate.passwordless.sudo.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 10.install.proxy.iam.compute.sh
            - 33.install.cost.control.sh
            - 70.install.enroot.pyxis.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/pclusterTagsAndBudget #make sure this policy is created https://pcluster.cloud/02-tutorials/04-cost-tracking.html
        S3Access:
          - BucketName: ${S3_BUCKET}
            EnableWriteAccess: true
      Networking:
        PlacementGroup:
          Enabled: false
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: cpu32
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 512
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: c6i-8xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: c6i.8xlarge
          MaxCount: 200
          MinCount: 0
        - Name: m6i-8xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: m6i.8xlarge
          MaxCount: 200
          MinCount: 0
        - Name: r6i-8xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: r6i.8xlarge
          MaxCount: 200
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 02.activate.passwordless.sudo.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 10.install.proxy.iam.compute.sh
            - 33.install.cost.control.sh
            - 70.install.enroot.pyxis.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/pclusterTagsAndBudget #make sure this policy is created https://pcluster.cloud/02-tutorials/04-cost-tracking.html
        S3Access:
          - BucketName: ${S3_BUCKET}
            EnableWriteAccess: true
      Networking:
        PlacementGroup:
          Enabled: false
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: cpu24
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 256
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: m5zn-6xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: m5zn.6xlarge
          MaxCount: 200
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 02.activate.passwordless.sudo.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 10.install.proxy.iam.compute.sh
            - 33.install.cost.control.sh
            - 70.install.enroot.pyxis.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/pclusterTagsAndBudget #make sure this policy is created https://pcluster.cloud/02-tutorials/04-cost-tracking.html
        S3Access:
          - BucketName: ${S3_BUCKET}
            EnableWriteAccess: true
      Networking:
        PlacementGroup:
          Enabled: false
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: cpu16
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 256
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: c6i-4xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: c6i.4xlarge
          MaxCount: 400
          MinCount: 0
        - Name: m6i-4xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: m6i.4xlarge
          MaxCount: 400
          MinCount: 0
        - Name: r6i-4xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: r6i.4xlarge
          MaxCount: 400
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 02.activate.passwordless.sudo.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 10.install.proxy.iam.compute.sh
            - 33.install.cost.control.sh
            - 70.install.enroot.pyxis.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/pclusterTagsAndBudget #make sure this policy is created https://pcluster.cloud/02-tutorials/04-cost-tracking.html
        S3Access:
          - BucketName: ${S3_BUCKET}
            EnableWriteAccess: true
      Networking:
        PlacementGroup:
          Enabled: false
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: spark
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 256
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: i3en-12xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: i3en.12xlarge
          MaxCount: 100
          MinCount: 0
        - Name: i3en-24xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: i3en.24xlarge
          MaxCount: 100
          MinCount: 0
        - Name: i4i-32xlarge
          DisableSimultaneousMultithreading: false
          InstanceType: i4i.32xlarge
          MaxCount: 100
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 02.activate.passwordless.sudo.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 10.install.proxy.iam.compute.sh
            - 33.install.cost.control.sh
            - 70.install.enroot.pyxis.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/pclusterTagsAndBudget #make sure this policy is created https://pcluster.cloud/02-tutorials/04-cost-tracking.html
        S3Access:
          - BucketName: ${S3_BUCKET}
            EnableWriteAccess: true
      Networking:
        PlacementGroup:
          Enabled: false
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
SharedStorage:
${FSX}
${ADMINFSX}
Tags:
  - Key: 1Click-HPC
    Value: 'true'
  - Key: 1Click-HPC-version
    Value: 'stability'
  - Key: map-migrated
    Value: ${MAP_MIGRATED}
  - Key: aws-parallelcluster-username
    Value: NA
  - Key: aws-parallelcluster-jobid
    Value: NA
  - Key: aws-parallelcluster-project
    Value: NA
DevSettings:
  Timeouts:
    HeadNodeBootstrapTimeout: 3600
    ComputeNodeBootstrapTimeout: 3600